Retry transaction write-write conflicts for CREATE SCHEMA (#155)
_TODO for Florian: Add logs to indicate write-write conflict and observe
behavior in real life_

The connector can receive parallel `CreateTable` gRPC requests, each
trying to create tables in the same schema. If the schema does not exist
yet, it is created via `CREATE SCHEMA IF NOT EXISTS`. However, we cannot
have multiple transactions in DuckDB that do this in parallel:

```python
>>> import duckdb
>>> con = duckdb.connect();
>>> c1 = con.cursor()
>>> c2 = con.cursor()
>>> c1.begin()
>>> c2.begin()
>>> c1.execute('CREATE SCHEMA IF NOT EXISTS my_schema')
# Success for c1
>>> c2.execute('CREATE SCHEMA IF NOT EXISTS my_schema')
Traceback (most recent call last):
  File "<python-input-7>", line 1, in <module>
    c2.execute('create schema if not exists my_schema')
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_duckdb.TransactionException: TransactionContext Error: Catalog write-write conflict on create with "my_schema"
```

When we retry the query, it will succeed because of the `IF NOT EXISTS`:
```python
>>> c1.commit()
>>> c2.rollback()
>>> c2.begin()
>>> c2.execute('create schema if not exists my_schema')
>>> c2.commit()
# Success for c2
```

In this PR, I implemented retries for `create_schema_if_not_exists` if
and only if the error is a write-write conflict. After a delay in the
range of `[0,100]`, the query is retried. The jitter is there to
decrease the chances of further conflicts when there are more than two
parallel `CreateTable` requests.

I added two new test cases and moved all parallel tests to
_test_server_parallel.cpp_.